### ISSUE TITLE
fix result window

### ISSUE THREAD

**Issue by johndoe71rus** [zwpwjwtz/f3-qt#3] opened 2017-03-22 15:26 UTC
Think need fix result window
[https://postimg.org/image/ocqmx8qvt](https://postimg.org/image/ocqmx8qvt)

lubuntu 14.04.

**Comment by zwpwjwtz** [comment] 2017-03-24 07:07
Confirmed.
This seems to be a common problem in many non-Qt-based desktop (LXDE, Unity and Cinnamon).
I'm trying to find if it is a dependency related issue, or it simply lacks some properties.

**Comment by zwpwjwtz** [comment] 2017-03-28 15:05
Fixed in 6af166b.

**Closed as completed** 2017-04-30 12:58 UTC
