### ISSUE TITLE
Rendering error in advanced screen while checking.

### ISSUE THREAD

**Issue by j12i** [zwpwjwtz/f3-qt#14] opened 2020-02-07 11:25 UTC
![2020-02-07 f3-qt](https://user-images.githubusercontent.com/2151851/74025316-fa88fd00-49a3-11ea-9a44-d002fa4d62b3.png)
compiled from master today (e9c251be6c101f5c636cf5ca8f16943be7ad82e5)
Qt 4.8.7
KDE runtime 4.14.3
Linux 4.4.208

- didn't use sudo. f3probe also works without sudo for me.
- I also have Qt5 installed.

( [console output](https://github.com/zwpwjwtz/f3-qt/files/4170509/2020-02-07.f3-qt.bug.report.txt) )

**Comment by zwpwjwtz** [comment] 2020-02-10 14:37
Thank you for the feedback. I guess the issue is related to Qt theme configuration (especially transparency rendering) in KDE environment, as I've tested it with Lubuntu 14.04 (LXDE + Qt 4.8.7) and it worked without problem. Coexisted Qt5 should not interfere with it if you build the program against Qt4 library.
I'll take time to look at it. However, as Qt4 becomes deprecated, maintenance of compatibility becomes painful, thus builds against Qt5 are preferred.

**Comment by zwpwjwtz** [comment] 2024-02-09 07:25
Fixed in 5087e1f.

**Closed as completed by zwpwjwtz** 2024-02-09 07:25 UTC
